name: client
description: A new Flutter application.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^4.3.1
  url_launcher: ^5.1.3
  share: ^0.6.4+3
  http: ^0.12.1
  flutter_secure_storage: ^3.3.3
  geolocator: ^4.0.3
  firebase_core:
  firebase_auth: 
  firebase_analytics:
  flutter_spinkit: ^4.1.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
    - lib/lang/en.json
    - lib/lang/mr.json
  fonts:
    # - family: Poppins
    #   fonts:
    #     - asset: fonts/Poppins-Medium.ttf
    #     - style: italic
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Medium.ttf
        - asset: fonts/Montserrat-ExtraLight.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
